# Generated by Django 4.2.6 on 2023-10-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
            ],
        ),
    ]
